CREATE TABLE public.room (
    id bigint generated by DEFAULT AS identity NOT NULL,
    code character varying NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT NOW(),
    current_game_id bigint NULL,
    CONSTRAINT room_pkey PRIMARY KEY (id),
    CONSTRAINT room_code_key UNIQUE (code)
) TABLESPACE pg_default;

ALTER TABLE public.room enable ROW LEVEL SECURITY;

ALTER TABLE public.room owner TO postgres;