CREATE TABLE public.tile (
    id bigint generated by DEFAULT AS identity NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT NOW(),
    word_id bigint NOT NULL,
    game_id bigint NOT NULL,
    team character varying NOT NULL,
    is_selected boolean NULL DEFAULT false,
    selected_by_user_id uuid NULL,
    position bigint NOT NULL,
    CONSTRAINT tile_pkey PRIMARY KEY (id),
    CONSTRAINT tile_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.game (id) ON DELETE CASCADE,
    CONSTRAINT tile_word_id_fkey FOREIGN KEY (word_id) REFERENCES public.word (id),
    CONSTRAINT tile_selected_by_user_id_fkey FOREIGN KEY (selected_by_user_id) REFERENCES public.player (id) ON DELETE
    SET NULL
) TABLESPACE pg_default;

ALTER TABLE public.tile enable ROW LEVEL SECURITY;

ALTER TABLE public.tile owner TO postgres;